### ISSUE TITLE
Review changes

### ISSUE THREAD

**Issue by postfalk** [tnc-ca-geo/extract#1]
@mmerrifield 

I made the basic changes in order to run the script on the new file formats and I added some flags to accommodate the new requirements. The new version needs Python 3 to run. 

I have already created an virtualenv on the server. Activate with 

```
source ~/scripts/env3/bin/activate
```

You can run the scripts like this:
```
$ cd ~/scripts/extract

$ python extract.py -v /home/devuser/data/AFMA/AUCF03-012029-181111_202044/videos -a /home/devuser/data/AFMA/AUCF03-012029-181111_202044/AUCF03-12029_labels_v010.csv -s /home/devuser/data/AFMA/test_stills -o -10 -w 20 -f 3
```

Your test_label.csv file won't work, it misses the header line. See README or 

```
python extract.py
```

for the meaning of option flags

The result of the test run above can be found in ~/data/AFMA/test_stills. Make sure to delete this directory before running the script with different settings into the same directory. 

There are a lot of nested directories in order to maintain information. I am awaiting further directions to refine the scripts.

The script is not yet universally applicable. I will add options and degrees of freedom as needed.

Falk

**Comment by mmerrifield** [comment]
can you add the -c flag back in for cropping

**Comment by mmerrifield** [comment]
and please change output format to:
stills_directory/filename_timestamp_label_l1_001.jpg


I will clean up labels in annotation file to be all lcase with _ instead of spaces

**Comment by postfalk** [comment]
- [x] c flag - re-added
- [x] filename template changed

**Comment by postfalk** [comment]
No need to clean that up. I can just convert. Should I add the camera to make sure that we do not overwrite to images of the same event?

**Comment by mmerrifield** [comment]
the camera number is in the video filename
