### ISSUE TITLE
Review extraction quality

### ISSUE THREAD

**Issue by postfalk** [tnc-ca-geo/extract#2]
Of course, we also need to review whether the extraction makes sense.

**Comment by postfalk** [comment]
At the first glance it seems to extract what we expect. Time window (20s), event offset (-10s), and sampling (3 fps) rate could probably be adjusted for better results.

**Comment by mmerrifield** [comment]
thanks Falk - I will look at both of these issues on either Thursday or Friday of this week

**Comment by mmerrifield** [comment]
extraction quality is perfect with default settings
