### ISSUE TITLE
extract.py - video file does not exist when it actually does

### ISSUE THREAD

**Issue by mmerrifield** [tnc-ca-geo/extract#3]
extract.py runs successfully for first ~100 lines of extract (that number varies but is between 95-150) then exits saying input video files do not exist - but they do. I can successfully re-run the code by creating a new extract.csv file that only contains video files at the point of failure onward (e.g. delete first ~100 records of events.csv).  

This problem also occurs when I run it against data I have locally

data to replicate problem are on fishnet server at
~/data/amr/AUCF03-012029-181111_202044

**Comment by postfalk** [comment]
I think that is finally solved. Sorry, I have not understood the problem for so long. I always thought, you got an actual Python FileNotFound error. This was tricky to find and easy to solve. It had to do with inner working of moviepy and how they are using subprocesses.
