### ISSUE TITLE
option to output video segments

### ISSUE THREAD

**Issue by mmerrifield** [tnc-ca-geo/extract#5]
hi Falk - would it be possible to add an option to output a video segment (instead of stills)

Ideally you could keep the option to create stills as well

thanks

**Comment by postfalk** [comment]
Yes, that is possible. How long should the segments be?
Falk


Falk Schuetzenmeister | Geospatial Software Engineer

The Nature Conservancy

t. 510.604.8010

s. 201 Mission St., Floor 4, San Francisco, CA 94105

e. falk.schuetzenmeister@tnc.org<mailto:falk.schuetzenmeister@tnc.org> | w. nature.org/california



 [cid:54cb3985-14d4-44d2-ad99-d54b8a34b1a5]



________________________________

**Comment by postfalk** [comment]
Done by 000b68d

Please use the -m option. I changed the script in a way that it stays backward compatible.
